# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: npm install
- script: npm test
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'App Insights DevExp(8980832b-9589-4ac2-b322-a6ae6a97f02b)'
    ScriptType: 'FilePath'
    ScriptPath: 'scripts/PublishTemplates.ps1'
    azurePowerShellVersion: 'LatestVersion'
    ScriptArguments: '$(StorageAccountKey)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: processedTemplates